/* JSON PIPELINE SCHEMA UPDATE */
/* Generated by Antigravity Agent */

-- 1. Add JSON columns to sketches/celit_jobs
ALTER TABLE public.sketches 
ADD COLUMN IF NOT EXISTS image_prompt_json jsonb,
ADD COLUMN IF NOT EXISTS video_prompt_json jsonb,
ADD COLUMN IF NOT EXISTS image_result jsonb,
ADD COLUMN IF NOT EXISTS provider_settings jsonb;

ALTER TABLE public.celit_jobs 
ADD COLUMN IF NOT EXISTS image_prompt_json jsonb,
ADD COLUMN IF NOT EXISTS video_prompt_json jsonb,
ADD COLUMN IF NOT EXISTS image_result jsonb;

-- 2. Create MetricsMule Template Table
CREATE TABLE IF NOT EXISTS public.image_prompt_templates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    template_name text NOT NULL,
    template_json jsonb NOT NULL,
    category text,
    created_at timestamptz DEFAULT now()
);

-- 3. Enable RLS on Templates
ALTER TABLE public.image_prompt_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read templates" ON public.image_prompt_templates;
CREATE POLICY "Public read templates" ON public.image_prompt_templates FOR SELECT USING (true);
