-- SECURITY HARDENING MIGRATION
-- Generated by Antigravity Agent

-- ==============================================================================
-- 1. HIGH RISK TABLES (Tokens, Secrets)
-- ==============================================================================

-- social_connections: Strict Owner Access
ALTER TABLE IF EXISTS public.social_connections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access social_connections" ON public.social_connections;
CREATE POLICY "Owner access social_connections" ON public.social_connections
    FOR ALL USING (auth.uid() = user_id);

-- Token Tables: Service Role Only (No Public Policies)
ALTER TABLE IF EXISTS public.prompt_portal_video_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.prompt_portal_cheat_codesrealism ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ai_video_engine_video_meta_tokens ENABLE ROW LEVEL SECURITY;

-- Disable public API access logic involves Supabase metadata which isn't standard SQL.
-- The user must do "Disable read access from public API" in dashboard if required, 
-- but RLS with no policies effectively blocks anon access anyway.

-- ==============================================================================
-- 2. USER CONTENT & LOGS
-- ==============================================================================

-- users
ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read own" ON public.users;
CREATE POLICY "Users read own" ON public.users FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Users update own" ON public.users;
CREATE POLICY "Users update own" ON public.users FOR UPDATE USING (auth.uid() = id);

-- agent_logs
ALTER TABLE IF EXISTS public.agent_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access agent_logs" ON public.agent_logs;
CREATE POLICY "Owner access agent_logs" ON public.agent_logs FOR ALL USING (auth.uid() = user_id);

-- campaigns
ALTER TABLE IF EXISTS public.campaigns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access campaigns" ON public.campaigns;
CREATE POLICY "Owner access campaigns" ON public.campaigns FOR ALL USING (auth.uid() = user_id);

-- content_items
ALTER TABLE IF EXISTS public.content_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access content_items" ON public.content_items;
CREATE POLICY "Owner access content_items" ON public.content_items FOR ALL USING (auth.uid() = user_id);

-- generated_content
ALTER TABLE IF EXISTS public.generated_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access generated_content" ON public.generated_content;
CREATE POLICY "Owner access generated_content" ON public.generated_content FOR ALL USING (auth.uid() = user_id);

-- scheduled_posts
ALTER TABLE IF EXISTS public.scheduled_posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access scheduled_posts" ON public.scheduled_posts;
CREATE POLICY "Owner access scheduled_posts" ON public.scheduled_posts FOR ALL USING (auth.uid() = user_id);

-- viral_content
ALTER TABLE IF EXISTS public.viral_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access viral_content" ON public.viral_content;
CREATE POLICY "Owner access viral_content" ON public.viral_content FOR ALL USING (auth.uid() = user_id);

-- viral_insights
ALTER TABLE IF EXISTS public.viral_insights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access viral_insights" ON public.viral_insights;
CREATE POLICY "Owner access viral_insights" ON public.viral_insights FOR ALL USING (auth.uid() = user_id);

-- yt_videos
ALTER TABLE IF EXISTS public.yt_videos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access yt_videos" ON public.yt_videos;
CREATE POLICY "Owner access yt_videos" ON public.yt_videos FOR ALL USING (auth.uid() = user_id);

-- yt_channels
ALTER TABLE IF EXISTS public.yt_channels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owner access yt_channels" ON public.yt_channels;
CREATE POLICY "Owner access yt_channels" ON public.yt_channels FOR ALL USING (auth.uid() = user_id);


-- ==============================================================================
-- 3. JOBS & QUEUES
-- ==============================================================================

-- celit_jobs: Public Read (Demo Req), Service Write
-- We allow SELECT true to ensure demo polling works without auth or with simplistic auth.
ALTER TABLE IF EXISTS public.celit_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read celit_jobs" ON public.celit_jobs;
CREATE POLICY "Public read celit_jobs" ON public.celit_jobs FOR SELECT USING (true);
-- No write policy => Service Role only.

-- miner_jobs: Service Role Only
ALTER TABLE IF EXISTS public.miner_jobs ENABLE ROW LEVEL SECURITY;

-- celit_seed_runs: Service Role Only
ALTER TABLE IF EXISTS public.celit_seed_runs ENABLE ROW LEVEL SECURITY;


-- ==============================================================================
-- 4. REFERENCE / METADATA TABLES (Public Read, Service Write)
-- ==============================================================================

-- Helper for public read
DO $$
DECLARE
    tables text[] := ARRAY[
        'prompt_portal_cinematic',
        'ai_video_engine_camera_cinematography',
        'ai_video_engine_cameraslenses',
        'ai_video_engine_directorsref_names',
        'prompt_generators_pg_variety',
        'prompt_portal_ai_video',
        'ai_video_engine_ai_video_prompts',
        'mega_prompts_database_ai_video'
    ];
    t text;
BEGIN
    FOREACH t IN ARRAY tables LOOP
        EXECUTE format('ALTER TABLE IF EXISTS public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Public read %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public read %I" ON public.%I FOR SELECT USING (true)', t, t);
    END LOOP;
END $$;


-- ==============================================================================
-- 5. FUNCTION SECURITY (search_path)
-- ==============================================================================

-- Set explicit search_path prevents malicious code from overriding standard operators/functions
-- We use DO block to handle potential missing functions gracefully if needed, 
-- but straightforward ALTER works if they exist.

ALTER FUNCTION public.get_random_seed(text, text, int4) SET search_path = public, pg_temp;
ALTER FUNCTION public.mark_seed_used(int8, int8, text) SET search_path = public, pg_temp;
ALTER FUNCTION public.get_random_prompts(int4, text) SET search_path = public, pg_temp;

-- Generic update function found in many supabase setups
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language plpgsql security definer set search_path = public, pg_temp;
