-- PROMPT PACKET PIPELINE SCHEMA
-- Generated by Antigravity Agent

-- 1. Image Prompt Packets (MetricsMule JSON)
CREATE TABLE IF NOT EXISTS public.image_prompt_packets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    vector text NOT NULL, -- 'LIFE', 'WORK', 'FEED'
    sketch_type text,     -- 'corporate_training', 'surveillance_feed', etc
    aesthetic_preset text, -- 'institutional_grey', 'neon_void', etc
    json_payload jsonb NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 2. Video Prompt Packets (Motion & Camera)
CREATE TABLE IF NOT EXISTS public.video_prompt_packets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    vector text NOT NULL,
    sketch_type text,
    aesthetic_preset text,
    motion_profile text,   -- 'slow_zoom', 'static_glitch', 'handheld_panic'
    json_payload jsonb NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 3. Add Selection Columns to Jobs
ALTER TABLE public.celit_jobs 
ADD COLUMN IF NOT EXISTS selected_image_packet_id uuid REFERENCES public.image_prompt_packets(id),
ADD COLUMN IF NOT EXISTS selected_video_packet_id uuid REFERENCES public.video_prompt_packets(id);

ALTER TABLE public.sketches
ADD COLUMN IF NOT EXISTS selected_image_packet_id uuid REFERENCES public.image_prompt_packets(id),
ADD COLUMN IF NOT EXISTS selected_video_packet_id uuid REFERENCES public.video_prompt_packets(id);

-- 4. Enable RLS
ALTER TABLE public.image_prompt_packets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read image packets" ON public.image_prompt_packets FOR SELECT USING (true);

ALTER TABLE public.video_prompt_packets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read video packets" ON public.video_prompt_packets FOR SELECT USING (true);


-- 5. Seed Initial Packets (For Immediate Testing)
-- Insert basic WORK packets so the pipeline doesn't crash on empty tables
INSERT INTO public.image_prompt_packets (vector, sketch_type, aesthetic_preset, json_payload)
VALUES 
('WORK_VECTOR', 'corporate_training', 'institutional_grey', '{
    "subject": "TIRED EMPLOYEE",
    "action": "staring at screen",
    "setting": "grey cubicle farm",
    "camera": "security camera grainy",
    "lighting": "fluorescent flicker",
    "style": "photorealistic depression",
    "meta_tokens": ["WORK_VECTOR", "bureaucracy"]
}'),
('LIFE_VECTOR', 'surveillance_feed', 'neon_void', '{
    "subject": "LONELY SHOPPER",
    "action": "holding frozen meal",
    "setting": "empty convenience store",
    "camera": "wide angle distortion",
    "lighting": "neon hum",
    "style": "liminal space",
    "meta_tokens": ["LIFE_VECTOR", "consumption"]
}')
ON CONFLICT DO NOTHING;

INSERT INTO public.video_prompt_packets (vector, sketch_type, aesthetic_preset, motion_profile, json_payload)
VALUES 
('WORK_VECTOR', 'corporate_training', 'institutional_grey', 'slow_zoom', '{
    "motion_type": "slow_creep",
    "camera_move": "slow push in",
    "subject_action": "blink once",
    "duration": 5,
    "fps": 24
}')
ON CONFLICT DO NOTHING;
